# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM+Json' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod "youtube-ios-player-helper"
  # Pods for MVVM+Json
	
  target 'MVVM+JsonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM+JsonUITests' do
    # Pods for testing
  end

end
